name: vnn
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - ffmpeg=4.3
  - freetype=2.10.4
  - gettext=0.21.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pillow=8.3.1
  - pip=21.2.4
  - python=3.9.7
  - pytorch=1.9.1
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.14.0
    - chex==0.0.8
    - dm-haiku==0.0.4
    - dm-tree==0.1.6
    - flatbuffers==2.0
    - jax==0.2.21
    - jaxlib==0.1.71
    - numpy==1.21.2
    - opt-einsum==3.3.0
    - optax==0.0.9
    - scipy==1.7.1
    - tabulate==0.8.9
    - toolz==0.11.1

